version: "2"

services:
    y2b_nginx:
        build:
          context: .
          dockerfile: ./nginx/Dockerfile
        container_name: y2b-nginx
        working_dir: /application
        volumes_from:
          - y2b_php_fpm

    y2b_php_fpm:
        build: php-fpm
        container_name: y2b-php-fpm
        working_dir: /application
        environment:
          - NODE_NAME=green