version: "2"

services:
    y2b_nginx:
      ports:
        - "5000:80"
      build:
        args:
          env: dev

    y2b_php_fpm:
      build:
        args:
          env: dev
      volumes:
         - ~/.composer/docker-cache/:/root/.composer:cached
         - ../../:/application

networks:
  default:
    external:
      name: youtube-network